name = "cruiserapp"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
name = "cruiserapp-production"

[env.staging]
name = "cruiserapp-staging" 

# Supabase configuration
# Remove D1 database config since we're using Supabase
# [[d1_databases]]
#    binding = "DB"
#    database_name = "cruiserapp-db"
#    database_id = "92342ab5-f4e1-4f31-aedd-cae13ae1ec55"

