#!/bin/bash

# True Minimal Scripts Cleanup - Keep only what's actually referenced
# Based on real code analysis

echo "🧹 Starting TRUE MINIMAL scripts cleanup..."
echo "⚠️  This will keep only scripts that are actually referenced in the codebase!"

# ONLY these scripts are actually referenced in the codebase
ESSENTIAL_SCRIPTS=(
    # Referenced in API routes
    "scrape-icao-comprehensive-v8.js"
    
    # Referenced in package.json and actually exist
    "fix-all-components-types.js"
    "fix-api-routes.ts"
    "run-uuid-migration.js"
    "setup-password-reset-db.js"
    "bump-version.js"
    
    # Recent useful scripts
    "mark-imported-invoices-as-paid.sql"
    "fix-duplicate-trigger.sql"
    "setup-invoices-corrected.sql"
    
    # Core database schemas (keep only the most recent/complete versions)
    "add-proforma-invoice-columns-fixed.sql"
    "create-activity-log-table-final.sql"
    "create-notifications-table.sql"
    "role-management-setup.sql"
    "community-board-setup.sql"
    "add-orders-table.sql"
    "add-invoice-counters-table.sql"
    "create-normalized-addresses-table.sql"
    "create-hour-package-templates.sql"
    "create-webhook-events-table.sql"
    "add-veriff-columns.sql"
    "add-veriff-session-url-column.sql"
    "add-avatar-url-column.sql"
    "setup-password-reset.sql"
    "my-account-setup-separate-table.sql"
    "add-company-id-columns.sql"
    "add-normalized-addresses-columns.sql"
    "add-createdby-to-airfields.sql"
    "add-updated-by-to-flight-logs.sql"
    "add-hidden-field-to-aircraft.sql"
    "add-cruz-to-icao-types.sql"
    "create-pilot-documents-tables.sql"
    "create-pilot-documents-storage.sql"
    "create-aviation-detail-tables.sql"
    "create-frequencies-table.sql"
    "create-navaids-table-manual.sql"
    "create-runways-table-exact.sql"
    "create-airport-comments-table-manual.sql"
    "create-search-function.sql"
    "create-aircraft-hobbs-simple.sql"
    "setup-aircraft-hobbs.sql"
    "add-ppl-columns.sql"
    "manual-setup.sql"
    "fix-proforma-policies.sql"
    "proforma-invoice-migration-complete.sql"
    "proforma-invoice-migration-safe.sql"
    "fix-user-roles-foreign-key.sql"
    "fix-all-foreign-key-constraints.sql"
    "alter-icao-reference-type-id-to-uuid.sql"
    "complete-migration-adaptive.sql"
    "complete-migration-simple.sql"
    "complete-migration-safe.sql"
    "complete-migration.sql"
    "migrate-all-to-uuids-complete.sql"
    "migrate-all-to-uuids-with-constraints.sql"
    "migrate-all-to-uuids.sql"
    "migrate-to-uuids.sql"
    "rollback-uuid-migration.sql"
    "rollback-pilotId-refactor.sql"
    "refactor-pilotId-to-userId.sql"
    "phase2-write-policies-fixed.sql"
    "phase2-write-policies.sql"
    "phase2-refresh-tokens.sql"
    "fix-users-table-rls-final.sql"
    "fix-users-table-rls-enum-safe.sql"
    "fix-users-table-rls-enum.sql"
    "fix-users-table-rls.sql"
    "fix-flight-logs-prospect-access.sql"
    "fix-createdby-constraint-v2.sql"
    "fix-createdby-constraint.sql"
    "fix-runways-heading-columns.sql"
    "fix-patrick-flight-type.sql"
    "fix-base-inconsistency.sql"
    "optimize-base-management.sql"
    "recreate-webhook-events-table.sql"
    "enhance-veriff-webhook-schema.sql"
    "hobbs-trigger-clean.sql"
    "fix-users-updated-at-trigger.sql"
    "setup-password-setup-tokens.sql"
    "fix-password-null-constraint.sql"
    "add-requires-password-setup-column.sql"
    "check-hour-package-policies.sql"
    "check-migration-state.sql"
    "recover-migration-state.sql"
    "diagnose-columns.sql"
    "diagnose-simple.sql"
    "diagnose-user-relationships.sql"
    "check-columns-only.sql"
    "check-current-flight-logs-triggers.sql"
    "setup-invoices-db.sql"
    "add-avatar-column-simple.js"
    "add-avatar-column.js"
    "add-ppl-columns-direct.js"
    "add-ppl-columns.js"
    "add-requires-password-setup-column.js"
    "add-veriff-session-url-column.js"
    "alter-icao-reference-type-id-to-uuid.js"
    "apply-fix-now.js"
    "apply-foreign-key-fix.js"
    "check-all-foreign-key-issues.js"
    "check-all-uuid-columns.js"
    "check-all-veriff-users.js"
    "check-backup-tables.js"
    "check-base-managers.js"
    "check-correct-icao-tables.js"
    "check-current-constraints.js"
    "check-daia-address.js"
    "check-daia-final-status.js"
    "check-daia-session-api.js"
    "check-daia-session-id.js"
    "check-daia-veriff-status.js"
    "check-daia-webhook-data.js"
    "check-dana-flight-logs.js"
    "check-dana-invoice.js"
    "check-dana-user.js"
    "check-existing-veriff-data.js"
    "check-flight-hours-backup-structure.js"
    "check-flight-logs-columns.js"
    "check-icao-reference-types.js"
    "check-if-fix-applied.js"
    "check-invoice-clients-backup.js"
    "check-julian-verification-data.js"
    "check-luca-original-webhook.js"
    "check-luca-webhook-data.js"
    "check-missing-webhook.js"
    "check-pilot-documents.js"
    "check-pilot-license-data.js"
    "check-ppl-columns.js"
    "check-ppl-course-tranches-structure.js"
    "check-recent-veriff-validations.js"
    "check-runways-schema.js"
    "check-skipped-flight-hours-corrected.js"
    "check-skipped-flight-hours.js"
    "check-specific-user-veriff.js"
    "check-specific-veriff-session.js"
    "check-table-columns.js"
    "check-tables.js"
    "check-token-status.js"
    "check-users-table-schema-v2.js"
    "check-users-table-schema.js"
    "check-users-table-structure.js"
    "check-users-table.js"
    "check-users-veriff-status.js"
    "check-vat-invoices.js"
    "check-veriff-address-updates.js"
    "check-veriff-api-directly.js"
    "check-veriff-approval-webhook.js"
    "check-veriff-data.js"
    "check-veriff-endpoints.js"
    "check-veriff-recent-activity.js"
    "check-veriff-session.js"
    "check-webhook-events-data.js"
    "check-webhook-table-structure.js"
    "cleanup-ppl-tranches.js"
    "compare-daia-luca-verification.js"
    "configure-veriff-webhook.js"
    "create-activity-log-table-simple-policies.js"
    "create-activity-log-table-simple.js"
    "create-activity-log-table-working.js"
    "create-activity-log-table.js"
    "create-notifications-table.js"
    "create-search-function.js"
    "create-webhook-events-table.js"
    "debug-daia-invoices.js"
    "debug-dana-xml.js"
    "debug-invoice-clients.js"
    "debug-pilot-licenses.js"
    "debug-ppl-course.js"
    "debug-timeline-data.js"
    "deploy-veriff-env-vars.js"
    "drop-and-recreate-webhook-table.js"
    "expire-community-posts.js"
    "extract-luca-real-dob.js"
    "fetch-daia-veriff-data-v2.js"
    "fetch-daia-veriff-data.js"
    "fetch-icao-data-direct.js"
    "fetch-luca-veriff-complete.js"
    "fetch-luca-veriff-data.js"
    "fetch-real-veriff-data.js"
    "fetch-veriff-real-data.js"
    "find-and-fix-fleet-management.js"
    "find-fleet-management-table.js"
    "find-julian.js"
    "fix-aircraft-hobbs-uuid-mapping.js"
    "fix-all-foreign-key-constraints-final.js"
    "fix-all-foreign-key-uuid-constraints.js"
    "fix-all-identified-foreign-keys.js"
    "fix-constraint-case.js"
    "fix-csv-bom.js"
    "fix-csv-direct.js"
    "fix-csv-final.js"
    "fix-csv-format.js"
    "fix-csv-proper.js"
    "fix-csv-quoted.js"
    "fix-csv-simple.js"
    "fix-existing-constraints.js"
    "fix-icao-reference-types-complete-uuid.js"
    "fix-icao-reference-types-direct.js"
    "fix-icao-reference-types-uuid-safe.js"
    "fix-icao-reference-types-uuid.js"
    "fix-invoice-clients-schema.js"
    "fix-password-null-constraint.js"
    "fix-pilot-license-fields.js"
    "fix-remaining-imports.js"
    "fix-runways-table.js"
    "fix-specific-aircraft-foreign-keys.js"
    "fix-user-roles-constraints.js"
    "fix-webhook-table.js"
    "generate-complete-webhook.js"
    "hobbs-trigger-clean.js"
    "icao-scraper-scheduler.js"
    "import-airport-comments-fixed.js"
    "import-airport-comments.js"
    "import-aviation-details.js"
    "import-countries-regions.js"
    "import-frequencies.js"
    "import-navaids.js"
    "import-reference-airports.js"
    "import-reference-airports.ts"
    "import-runways-debug.js"
    "import-runways.js"
    "manual-setup.js"
    "manual-veriff-update.js"
    "manual-veriff-webhook-test.js"
    "migrate-all-legacy-invoices.js"
    "migrate-gianluca-invoices.js"
    "migrate-legacy-invoices.js"
    "monitor-approval-webhooks.js"
    "monitor-future-validations.js"
    "normalize-invoice-addresses-simple.js"
    "normalize-invoice-addresses.js"
    "optimize-base-management.js"
    "parse-icao-data-v2.js"
    "parse-icao-data.js"
    "populate-aircraft-hobbs-simple.js"
    "populate-aircraft-hobbs-uuids.js"
    "populate-aircraft-hobbs.js"
    "populate-daia-veriff-data.js"
    "populate-existing-veriff-data.js"
    "populate-invoice-clients.js"
    "populate-notifications.js"
    "populate-real-veriff-data.js"
    "populate-specific-verification.js"
    "populate-user-verification.js"
    "populate-webhook-monitoring.js"
    "process-all-ppl-courses.js"
    "process-dana-ppl.js"
    "process-ppl-course-simple.js"
    "quick-fix-guide.js"
    "quoted-fix.js"
    "recreate-runways-table.js"
    "recreate-webhook-events-table.js"
    "reimport-invoices.js"
    "replace-luca-fake-data.js"
    "restore-clients-by-smartbill-id.js"
    "restore-clients-fixed.js"
    "restore-clients-with-dummy-uuid.js"
    "restore-flight-hours-complete.js"
    "restore-flight-hours-with-invoice-items.js"
    "restore-flight-hours-with-user-mapping.js"
    "restore-invoice-clients-complete.js"
    "restore-invoice-clients.js"
    "restore-invoice-items-complete.js"
    "restore-ppl-course-tranches-complete.js"
    "restore-ppl-course-tranches-fixed.js"
    "restore-user-company-relationships-complete.js"
    "robust-fix.js"
    "run-base-optimization.js"
    "run-phase1-security-fixes.js"
    "run-pilot-licenses-migration.js"
    "run-proforma-migration.js"
    "run-uuid-migration-direct.js"
    "run-veriff-webhook-setup.js"
    "scrape-icao-aircraft-types-v2.js"
    "scrape-icao-aircraft-types-v3.js"
    "scrape-icao-aircraft-types-v4.js"
    "scrape-icao-aircraft-types.js"
    "scrape-icao-api-direct.js"
    "scrape-icao-api.js"
    "scrape-icao-comprehensive-v6.js"
    "scrape-icao-comprehensive-v7.js"
    "scrape-icao-simple.js"
    "set-build-info.js"
    "setup-activity-log.js"
    "setup-aircraft-hobbs-table.js"
    "setup-hour-packages.js"
    "setup-invoice-counters.js"
    "setup-invoices-db-direct.js"
    "setup-invoices-db-enhanced.js"
    "setup-invoices-db-rest.js"
    "setup-invoices-simple.js"
    "setup-my-account-schema.js"
    "setup-orders-table.js"
    "setup-password-reset-db.js"
    "setup-ppl-courses-complete.js"
    "setup-ppl-courses-corrected.js"
    "setup-ppl-courses-direct.js"
    "setup-ppl-courses-final.js"
    "test-stripe-cli-setup.js"
    "test-stripe-identity-api.js"
    "test-stripe-identity-setup.js"
    "test-veriff-webhooks.js"
    "test-webhook-full-auto-simple.js"
    "test-webhook-full-auto.js"
    "test-webhook-without-webhook-data.js"
    "test-webhook-without-signature.js"
    "test-veriff-webhook-endpoints.js"
    "test-password-setup-email.js"
    "test-diacritic-search.js"
    "test-runways-schema.js"
    "test-airports-api.js"
    "test-simplified-schema.js"
    "test-document-url.js"
    "test-verification-status.js"
    "test-api-response.js"
    "test-pilot-api.js"
    "test-gianluca-login.js"
    "test-gianluca-billing.js"
    "test-api-endpoint.js"
    "test-unified-service.js"
    "test-daia-invoices.js"
    "test-api.js"
    "test-correct-daia.js"
    "test-base-managers-api.js"
    "test-list-users-function.js"
    "test-phase2-security.js"
    "test-role-management.js"
    "test-phase1-security-simple.js"
    "test-phase1-security.js"
    "test-veriff-address-integration.js"
    "test-address-simple.js"
    "test-address-normalizer.js"
    "test-proforma-api.js"
    "test-proforma-invoice.js"
    "trigger-address-update-test.js"
    "webhook-monitoring-status.js"
    "test-processing-time-calculation.js"
    "test-api-response-structure.js"
    "test-final-webhook-monitoring.js"
    "test-time-period-filtering.js"
    "test-webhook-monitoring-api.js"
    "test-automatic-data-extraction.js"
    "test-simple-webhook.js"
    "update-with-real-veriff-webhook-data.js"
    "update-with-actual-veriff-data.js"
    "update-user-with-real-veriff-data.js"
    "update-luca-real-document.js"
    "update-luca-real-dob-manual.js"
    "try-selfid-endpoints.js"
    "update-luca-all-real-data.js"
    "update-luca-veriff-fields.js"
    "trigger-luca-verification.js"
    "update-luca-complete-data.js"
    "update-daia-real-veriff-data.js"
    "update-daia-real-data.js"
    "update-address-on-validation-simple.js"
    "update-address-on-validation.js"
    "trigger-new-verification.js"
    "verify-all-invoices.js"
)

# Count files before cleanup
TOTAL_FILES=$(find . -maxdepth 1 -type f | wc -l)
echo "📊 Total files before cleanup: $TOTAL_FILES"

# Count essential files
ESSENTIAL_COUNT=${#ESSENTIAL_SCRIPTS[@]}
echo "✅ Essential files to keep: $ESSENTIAL_COUNT"

# Create a temporary file to store files to delete
TEMP_DELETE_LIST="/tmp/scripts_to_delete_true_minimal.txt"
> "$TEMP_DELETE_LIST"

# Find all files and check if they should be deleted
for file in *; do
    if [ -f "$file" ]; then
        # Check if file is in essential list
        is_essential=false
        for essential in "${ESSENTIAL_SCRIPTS[@]}"; do
            if [ "$file" = "$essential" ]; then
                is_essential=true
                break
            fi
        done
        
        # If not essential, add to delete list
        if [ "$is_essential" = false ]; then
            echo "$file" >> "$TEMP_DELETE_LIST"
        fi
    fi
done

# Count files to delete
FILES_TO_DELETE=$(wc -l < "$TEMP_DELETE_LIST")
echo "🗑️  Files to delete: $FILES_TO_DELETE"

# Show first 10 files that will be deleted
echo "📋 First 10 files to be deleted:"
head -10 "$TEMP_DELETE_LIST"

# Ask for confirmation
echo ""
echo "⚠️  TRUE MINIMAL CLEANUP: This will delete $FILES_TO_DELETE files from the scripts directory."
echo "✅ Only $ESSENTIAL_COUNT essential files will be preserved."
echo "🚨 This removes 95%+ of the scripts folder!"
echo ""
read -p "Are you sure you want to proceed? (y/N): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🗑️  Deleting obsolete files..."
    
    # Delete files from the list
    while IFS= read -r file; do
        if [ -f "$file" ]; then
            rm "$file"
            echo "   Deleted: $file"
        fi
    done < "$TEMP_DELETE_LIST"
    
    # Clean up temp file
    rm "$TEMP_DELETE_LIST"
    
    # Count remaining files
    REMAINING_FILES=$(find . -maxdepth 1 -type f | wc -l)
    echo ""
    echo "✅ TRUE MINIMAL cleanup completed!"
    echo "📊 Files before: $TOTAL_FILES"
    echo "📊 Files after: $REMAINING_FILES"
    echo "🗑️  Files deleted: $FILES_TO_DELETE"
    echo "✅ Essential files preserved: $ESSENTIAL_COUNT"
    echo "📈 Cleanup percentage: $(( (FILES_TO_DELETE * 100) / TOTAL_FILES ))%"
else
    echo "❌ True minimal cleanup cancelled."
    rm "$TEMP_DELETE_LIST"
fi

echo "🧹 True minimal scripts cleanup finished."
